controllers:
    resource: ../src/Controller/
    type: attribute

kernel:
    resource: ../src/Kernel.php
    type: annotation

api_login_check:
    path: api/login_check

# config/routes.yaml
api_refresh_token:
    path: /api/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh